#ifndef NSRREADER_H_
#define NSRREADER_H_

#include <bbndk.h>

#if !defined (BBNDK_VERSION_AT_LEAST)
#define BBNDK_VERSION_ENCODE(major, minor, patch) \
    (((major)*1000000)+((minor)*1000)+(patch))
#define BBNDK_VERSION_CURRENT_MAJOR 10
#define BBNDK_VERSION_CURRENT_MINOR 0
#define BBNDK_VERSION_CURRENT_PATCH 0
#define BBNDK_VERSION_CURRENT BBNDK_VERSION_ENCODE(BBNDK_VERSION_CURRENT_MAJOR,BBNDK_VERSION_CURRENT_MINOR,BBNDK_VERSION_CURRENT_PATCH)
#define BBNDK_VERSION_AT_LEAST(major, minor, patch) \
    (BBNDK_VERSION_CURRENT >= BBNDK_VERSION_ENCODE(major, minor, patch))
#endif

#endif /* NSRREADER_H_ */
